const imgPath = "../assets/img/";
const audioPath = "../assets/audio/";

const songs = [
  {
    id: 1,
    title: 'Right_Now_Na_Na',
    artist: 'Akon',
    artwork: require('../assets/img/img1.jpg'),
    url: require(audioPath + `rightNow.mp3`),
  },
  {
    id: 2,
    title: 'Set_Fire_To_The_Rain',
    artist: 'Adele',
    artwork: require('../assets/img/img2.jpg'),
    url: require(audioPath + 'setfire.mp3'),
  },
  {
    id: 3,
    title: 'Fairy_Tale',
    artist: 'Alexander_rybak',
    artwork: require('../assets/img/img3.jpg'),
    url: require(audioPath + 'fairyTale.mp3'),
  },
  {
    id: 4,
    title: 'Luv_Money',
    artist: 'Amaarae',
    artwork: require('../assets/img/img4.jpg'),
    url: require(audioPath + 'loveMoney.mp3'),
  },
  {
    id: 5,
    title: 'Animals X Starboy',
    artist: 'Starboy',
    artwork: require('../assets/img/img5.jpg'),
    url: require(audioPath + 'starBoy.mp3'),
  },
  {
    id: 6,
    title: 'Heart_So_Good',
    artist: 'Astrid_S',
    artwork: require('../assets/img/img6.jpg'),
    url: require(audioPath + 'soGood.mp3'),
  },
  {
    id: 7,
    title: 'Attention',
    artist: 'Charlie-puth',
    artwork: require('../assets/img/img7.jpg'),
    url: require(audioPath + 'attention.mp3'),
  },
  {
    id: 8,
    title: 'Into_Your_Arms',
    artist: 'Ava_Max',
    artwork: require('../assets/img/img8.jpg'),
    url: require(audioPath + 'yourArms.mp3'),
  },
  {
    id: 9,
    title: 'Living_Hell',
    artist: 'Bella_Poarch',
    artwork: require('../assets/img/img9.jpg'),
    url: require(audioPath + 'hell.mp3'),
  },
  {
    id: 10,
    title: 'Lovely',
    artist: 'Billie_Eilish',
    artwork: require('../assets/img/img10.jpg'),
    url: require(audioPath + 'lovely.mp3'),
  },
  {
    id: 11,
    title: 'One_Kiss',
    artist: 'Dua_Lipa',
    artwork: require('../assets/img/img11.jpg'),
    url: require(audioPath + 'kiss.mp3'),
  },
  {
    id: 12,
    title: 'Shameless',
    artist: 'Camila_Cabello',
    artwork: require('../assets/img/img12.jpg'),
    url: require(audioPath + 'shame.mp3'),
  },
  {
    id: 13,
    title: 'Cardigan',
    artist: 'Taylor_Swift',
    artwork: require('../assets/img/img13.jpg'),
    url: require(audioPath + 'card.mp3'),
  },
  {
    id: 14,
    title: 'Under_the_Influence',
    artist: 'Chris_Brown',
    artwork: require('../assets/img/img14.jpg'),
    url: require(audioPath + 'influence.mp3'),
  },
  {
    id: 15,
    title: 'Dandelions',
    artist: 'Ruth_B',
    artwork: require('../assets/img/img15.jpg'),
    url: require(audioPath + 'Dandel.mp3'),
  },
  {
    id: 16,
    title: 'Dark_Paradise',
    artist: 'Lana_Del_Rey',
    artwork: require('../assets/img/img16.jpg'),
    url: require(audioPath + 'dark.mp3'),
  },
  {
    id: 17,
    title: `I'm_Good`,
    artist: 'Bebe_Rexha',
    artwork: require('../assets/img/img17.jpg'),
    url: require(audioPath + 'good.mp3'),
  },
  {
    id: 18,
    title: 'DayLight',
    artist: 'David_Kushner',
    artwork: require('../assets/img/img18.jpg'),
    url: require(audioPath + 'day.mp3'),
  },
  {
    id: 19,
    title: 'Love_Me_Like_U_Do',
    artist: 'Ellie_Goulding',
    artwork: require('../assets/img/img19.jpg'),
    url: require(audioPath + 'LoveMe.mp3'),
  },
  {
    id: 20,
    title: 'Calm_down',
    artist: 'Selena_Gomez',
    artwork: require('../assets/img/img20.jpg'),
    url: require(audioPath + 'calm.m4a'),
  },
  {
    id: 21,
    title: 'Eyes_Dont_Lie',
    artist: 'Isabel_LaRosa',
    artwork: require('../assets/img/img21.jpg'),
    url: require(audioPath + 'Eyes.mp3'),
  },
  {
    id: 22,
    title: 'SomeWhere_Only_We_Know',
    artist: 'Nightcore',
    artwork: require('../assets/img/img22.jpg'),
    url: require(audioPath + 'someWhere.mp3'),
  },
  {
    id: 23,
    title: 'Night_Changes',
    artist: 'One_Direction',
    artwork: require('../assets/img/img23.jpg'),
    url: require(audioPath + 'night.mp3'),
  },
  {
    id: 24,
    title: 'Diamonds',
    artist: 'Rihanna',
    artwork: require('../assets/img/img24.jpg'),
    url: require(audioPath + 'diamond.mp3'),
  }, {
    id: 25,
    title: 'People_U_Know',
    artist: 'Selena_Gomez',
    artwork: require('../assets/img/img25.jpg'),
    url: require(audioPath + 'People.mp3'),
  },
  {
    id: 26,
    title: 'Cheap_Thrills',
    artist: 'Sia',
    artwork: require('../assets/img/img26.jpg'),
    url: require(audioPath + 'cheap.mp3'),
  },
  {
    id: 27,
    title: 'Wishes',
    artist: 'Talwinder',
    artwork: require('../assets/img/img27.jpg'),
    url: require(audioPath + 'wish.mp3'),
  },
  {
    id: 28,
    title: 'Until_I_Found_You',
    artist: 'Stephen_Sanchez',
    artwork: require('../assets/img/img28.jpg'),
    url: require(audioPath + 'Until.mp3'),
  },
  {
    id: 29,
    title: 'Dusk_till_Down',
    artist: 'Zayn_Malik',
    artwork: require('../assets/img/img29.jpg'),
    url: require(audioPath + 'duck.mp3'),
  },
];

export default songs;